/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        slateDark: {
          bg: 'rgb(var(--color-bg) / <alpha-value>)',
          surface: 'rgb(var(--color-surface) / <alpha-value>)',
          surfaceSubtle: 'rgb(var(--color-surface-subtle) / <alpha-value>)',
          'surface-subtle': 'rgb(var(--color-surface-subtle) / <alpha-value>)',
          border: 'rgb(var(--color-border) / <alpha-value>)',
          borderSubtle: 'rgb(var(--color-border-subtle) / <alpha-value>)',
          'border-subtle': 'rgb(var(--color-border-subtle) / <alpha-value>)',
          text: 'rgb(var(--color-text) / <alpha-value>)',
          textMuted: 'rgb(var(--color-text-muted) / <alpha-value>)',
          'text-muted': 'rgb(var(--color-text-muted) / <alpha-value>)',
          primary: 'rgb(var(--color-primary) / <alpha-value>)',
          primaryHover: 'rgb(var(--color-primary-hover) / <alpha-value>)',
          'primary-hover': 'rgb(var(--color-primary-hover) / <alpha-value>)',
          primaryLight: 'rgb(var(--color-primary-light) / <alpha-value>)',
          'primary-light': 'rgb(var(--color-primary-light) / <alpha-value>)',
          chatBg: 'rgb(var(--color-chat-bg) / <alpha-value>)',
          'chat-bg': 'rgb(var(--color-chat-bg) / <alpha-value>)',
          like: '#F43F5E',
          dislike: '#F59E0B',
          success: '#10B981',
        },
      },
    },
  },
  plugins: [],
};
